---
- hosts: icinga-db
  user: ec2-user
  sudo: yes
  vars:
  - mysql_root_password: "secretpass"

  tasks:
    - name: Install MySQL
      action: yum name={{item}}
      with_items:
        - MySQL-python
        - mariadb
        - mariadb-server

    - name: Start the MySQL service
      action: service name=mariadb state=started

    - name: delete anonymous MySQL server user for server 
      mysql_user: login_user=root
                  login_password='{{ mysql_root_password }}'
                  check_implicit_admin=yes
                  user=""
                  host={{ item }}
                  state="absent"
      with_items:
        - ""
        - localhost

    - name: Change root user password on first run
      mysql_user: login_user=root
                  login_password="{{ mysql_root_password }}"
                  check_implicit_admin=yes
                  name=root
                  password={{ mysql_root_password }}
                  priv=*.*:ALL,GRANT
                  host={{ item }}
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: remove the MySQL test database
      action: mysql_db login_user=root login_password="{{ mysql_root_password }}" db=test state=absent
      
   - name: Create a new database with name 'icinga'
     mysql_db:
       name: icinga
       state: present
  
    - name: create user icinga for database icinga 
      mysql_user:
        name: icinga
        password: password
        priv: '*.*:ALL,GRANT'
        state: present

