---
- hosts: all
  remote_user: xxxxxx
  become: yes
  become_method: su
  tasks:
    - name: Create nagios
      user: name=nagios shell=/bin/bash home=/opt/nagios groups=nagios generate_ssh_key=yes ssh_key_bits=2048
    - name: Set password to user
      shell: echo nagios:secretpasswd | sudo chpasswd
      no_log: True
    - name: install the latest version of Wget
      yum:
        name: wget
        state: latest
    - name: Add epel repository public key
      rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        state: present
    - name: Download EPEL YUM repo
      shell: wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -P /tmp
    - name: Install EPEL YUM repo
      shell: rpm -ivh /tmp/epel-release-latest-7.noarch.rpm
    - name: install the latest version of NRPE from epel repo
      yum: pkg=nrpe state=installed
    - name: Add local ip to allowed_hosts on /etc/nagios/nrpe.cfg
      lineinfile: dest=/etc/nagios/nrpe.cfg regexp='^allowed_hosts.*' line='allowed_hosts=127.0.0.1,x.x.x.x' state=present
      notify:
      - restart nrpe
    - name: ensure nrpe is running (and enable it at boot)
      service: name=nrpe state=started enabled=yes
  handlers:
    - name: restart nrpe
      service: name=nrpe state=restarted
